#!/bin/bash
if [ `git rev-parse --abbrev-ref HEAD` == "gh-pages" ] ; then exit ; fi
git stash save --include-untracked --all;git checkout gh-pages
rm *
rm -r doxygen
git checkout master doxygen
cp doxygen/html/* .
rm index.html
cp piemod_8cpp.html index.html
git add .
git commit -a -m "Updating site."
git clean -df
git checkout master;git stash pop